### PR TITLE
Check the error on *Cmd.Start()

### PR DESCRIPTION
**Pull request by kron4eg**
cc @FLYBYME

### CODE REVIEW

**Comment by kron4eg** [comment]
it causes problems in https://github.com/gliderlabs/herokuish/issues/87

**Comment by progrium** [comment]
Should it really provide exit status 0?

**Comment by kron4eg** [comment]
@progrium this is indeed good question, I've used 0 because same style is used in the same function above: https://github.com/progrium/go-basher/blob/master/basher.go#L226-L228

But I think it should be at least -1, in both cases.

**Comment by josegonzalez** [comment]
I'm going to merge this as is. I think we can decide if this should fail in a separate PR (I think it should, probably exit 1 or something).

**Pull request merged**
